//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PickID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int CodeToRecieve { get; set; }
        public string Status { get; set; }
        public int Count { get; set; }
        public int ProductID { get; set; }
    
        public virtual PickPoints PickPoints { get; set; }
        public virtual Products Products { get; set; }
        public virtual User User { get; set; }
    }
}
